### ISSUE TITLE
[求助] github action 构建页面时报错

### ISSUE THREAD

**Issue by HeavenTonight** [razonyang/hugo-theme-bootstrap-skeleton#41]
大神 你好，我在使用模板构建页面时，流水线出现一下的错误，可否帮忙给点修改建议。谢谢
日志信息如下：
https://github.com/HeavenTonight/HeavenTonight.github.io/actions/runs/7690916860/job/20955424687
![image](https://github.com/razonyang/hugo-theme-bootstrap-skeleton/assets/44971607/8f03fa4f-96b9-4ba7-8b0a-2d8bc38e695e)

**Comment by razonyang** [comment]
请尝试升级主题看看，https://hbs.razonyang.com/v1/zh-hans/docs/getting-started/upgradation/

**Comment by HeavenTonight** [comment]
> 请尝试升级主题看看，https://hbs.razonyang.com/v1/zh-hans/docs/getting-started/upgradation/

好的 感谢，已经解决，是因为``` hugo-theme-bootstrap ```的版本没有使用``` Git Submodule ``` 更新。
